create table Connection (
	ID INT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Description TEXT NULL,
	URL VARCHAR(200) NOT NULL,
	User VARCHAR(50) NOT NULL,
	Password VARCHAR(200) NULL,
	Driver_ID INT UNSIGNED NOT NULL,
	Test TEXT NULL,
	Timeout INT NOT NULL DEFAULT 0,
	CONSTRAINT fk_driver_id FOREIGN KEY (Driver_ID) REFERENCES Driver (ID)
)ENGINE = InnoDB;